# Example hardware + experiment config for the electrolyte mixer/optimizer (8 chemicals)

serial:
  pump_controller_A:
    port: "COM5"
    # Calibrations for channels 0..3 (ml per second) at default_pwm
    ml_per_s: [0.094, 0.094, 0.094, 0.094]
    default_pwm: 0.60
  pump_controller_B:
    port: "COM6"
    ml_per_s: [0.094, 0.094, 0.094, 0.094]
    default_pwm: 0.60

  temperature_controller:
    port: "COM9"

  squidstat:
    # If your squidstat.py uses another constructor arg (e.g., device index), adapt here.
    port: "COM11"

measurements:
  # Root directory for results (your measurements() helper manages subfolders/mode files)
  results_root: "./results"

# Map each chemical to its controller/pump index and prime volume to fill the tubing.
# pump_index is 1..4 for each controller.
chemicals:
  Chem1: { controller: "A", pump_index: 1, prime_ml: 6.0 }
  Chem2: { controller: "A", pump_index: 2, prime_ml: 6.0 }
  Chem3: { controller: "A", pump_index: 3, prime_ml: 6.0 }
  Chem4: { controller: "A", pump_index: 4, prime_ml: 6.0 }
  Chem5: { controller: "B", pump_index: 1, prime_ml: 6.0 }
  Chem6: { controller: "B", pump_index: 2, prime_ml: 6.0 }
  Chem7: { controller: "B", pump_index: 3, prime_ml: 6.0 }
  Chem8: { controller: "B", pump_index: 4, prime_ml: 6.0 }

# Default pump parameters used by the scheduler for priming / single‑channel dosing.
pumps:
  defaults:
    pwm: 0.60

temperature:
  setpoints_C: [5.0, 20.0, 40.0]
  tolerance_C: 0.3
  timeout_s: 1800
  soak_s: 120

eis:
  current_A: 0.0
  freq_start_Hz: 10000.0
  freq_stop_Hz: 0.5
  ppd: 8

# Optional quick-start recipe (ml per chemical). Used by scheduler.__main__ only.
example_recipe_ml:
  Chem1: 5.0
  Chem2: 2.5
  Chem3: 1.0
  Chem4: 1.5
  Chem5: 0.0
  Chem6: 0.0
  Chem7: 0.0
  Chem8: 0.0
