measurements:
  results_root: ./results/
  user: Wessel
  project: MOFESS
  electrolyte: KCl # Will be overwritten if new mixture is created.
  cell_constant: 3 # /cm
  cell_volume: 2.4 # ml

# Optional quick-start recipe (ml per chemical).
recipe_ml:
  Milli-Q: 0.8
  Ethanol: 0.1
  Chem3: 0.2
  Chem4: 1.0
  Chem5: 0.0
  Chem6: 0.0
  Chem7: 0.5
  Chem8: 0.0

# Map each chemical to its controller/pump index and prime volume to fill the tubing.
# pump_index is 1..4 for each controller.
# cost is per ml
chemicals:
  Milli-Q: { controller: A, pump_index: 1, prime_ml: 0.2, cost: 0 }
  Ethanol: { controller: A, pump_index: 2, prime_ml: 0.2, cost: 1 }
  Chem3: { controller: A, pump_index: 3, prime_ml: 0.2, cost: 1 }
  Chem4: { controller: A, pump_index: 4, prime_ml: 0.2, cost: 1 }
  Chem5: { controller: B, pump_index: 1, prime_ml: 2.0, cost: 1 }
  Chem6: { controller: B, pump_index: 2, prime_ml: 2.0, cost: 1 }
  Chem7: { controller: B, pump_index: 3, prime_ml: 2.0, cost: 1 }
  Chem8: { controller: B, pump_index: 4, prime_ml: 2.0, cost: 1 }

volumes:
  # Tube volumes between destinations
  mix_to_cell_ml: 0.5
  cell_to_waste_ml: 2.0
  waste_no: 1 # 1..4
  flush_ml: 2.4

# Default pump parameters used by the scheduler for priming / dosing.
pumps:
  # Calibration for stepper pumps (currently hardcoded in firmware)
  ml_per_rev: 0.094
  # Calibration for DC pumps
  default_pwm: 60
  ml_per_s: 0.5

temperature:
  setpoints_C: [0.0, 10.0, 20.0, 40.0]
  tolerance_C: 0.25 # plus or minus
  steady_s: 120
  timeout_s: 1800
  settle_s: 60
  cleaning_s: 120

eis:
  freq_start_Hz: 85000
  freq_end_Hz: 1
  amplitude_v: 0.01
  bias_v: 0
  ppd: 20
  measurements_per_temp: 3 # minimum to give error bars

cv:
  first_limit_V: -1.5
  second_limit_V: 1.5
  scan_rate: 0.1
  sampling_interval_s: 0.1
  cycles: 3
  measurements_per_temp: 3 # minimum to give error bars

serial:
  pump_controller_A: # Has 2x DC transfer pumps
    port: /dev/cu.wchusbserial110
    baud: 115200
    mock: False

  pump_controller_B: # Has 4x DC waste pumps
    port: COM6
    baud: 115200
    mock: True

  temperature_controller:
    port: COM9
    baud: 115200
    mock: True

  squidstat:
    port: COM11
    channel: 0
    instrument: Plus2695
    mock: True