measurements:
  results_root: ./results/
  user: Wessel
  project: MOFESS
  electrolyte: KCl # Will be overwritten if new mixture is created.
  cell_constant: 3 # /cm
  electrolyte_volume: 1.5 # ml (must match atinary total volume)
  cell_volume: 2.0 # ml (used for transfer and cleaning)

# Tube lengths mm:
# Inside Boxer Pumps = 65 (0,19ml)
# Inside DC Pumps = 150 (0.44ml)
# Bottle to Pump = 395 (1,15ml => 0,0029114 ml/mm)
# Pumps to Needles = 100, 
# Mixer to Cell = 50+150+85 (0.83ml)
# Cell to Waste = 200+95+.. (0.86ml)
# Waste Length = 300 (0.88ml)
# Waste Spacing = 110 (0.32ml)

# Map each chemical to its controller/pump index and prime volume to fill the tubing.
# pump_index is 1..4 for each controller, cost is per ml

chemicals:
  Milli-Q: { controller: A, pump_index: 1, prime_ml: 1.7, cost: 0.01 }
  Ethanol: { controller: A, pump_index: 2, prime_ml: 1.0, cost: 0.5 }
  KCl: { controller: A, pump_index: 3, prime_ml: 1.0, cost: 4 }
  Chem4: { controller: A, pump_index: 4, prime_ml: 1.0, cost: 1 }
  Chem5: { controller: B, pump_index: 1, prime_ml: 1.0, cost: 1 }
  Chem6: { controller: B, pump_index: 2, prime_ml: 1.0, cost: 1 }
  Chem7: { controller: B, pump_index: 3, prime_ml: 1.0, cost: 1 }
  Chem8: { controller: B, pump_index: 4, prime_ml: 1.0, cost: 1 }

system:
  # Tube volumes between destinations
  mix_to_cell_ml: 0.83
  cell_to_waste_ml: 2.5
  waste_no: 1 # 1..4

# Default pump parameters used by the scheduler for priming / dosing.
pumps:
  # Calibration for stepper pumps (currently hardcoded in firmware)
  ml_per_rev: 0.094
  mixing_flowrate: 0.2 # ml/s
  priming_flowrate: 0.2
  # Calibration for DC pumps
  transfer_pwm: 70 # %
  waste_pwm: 70
  ml_per_s: 0.4

temperature:
  setpoints_C: [-20] #[0.0, 10.0, 20.0, 40.0]
  tolerance_C: 0.25 # plus or minus
  steady_s: 120
  timeout_s: 1800
  settle_s: 60
  cleaning_s: 60

eis:
  freq_start_Hz: 85000
  freq_end_Hz: 1
  amplitude_v: 0.01
  bias_v: 0
  ppd: 20
  measurements_per_temp: 3 # minimum to give error bars

cv:
  first_limit_V: -1.5
  second_limit_V: 1.5
  scan_rate: 0.1
  sampling_interval_s: 0.1
  cycles: 3
  measurements_per_temp: 3 # minimum to give error bars

communication:
  pump_controller_A: # Has 2x DC transfer pumps
    ble_name: PumpControllerA
    mock: False
    timeout: 60

  pump_controller_B: # Has 4x DC waste pumps
    ble_name: PumpControllerB
    mock: False
    timeout: 60

  temperature_controller:
    port: /dev/cu.usbserial-CLEBb136G04
    baud: 115200
    mock: False

  squidstat:
    port: /dev/cu.usbmodem111101
    channel: 0
    instrument: Plus2695
    mock: True