measurements:
  results_root: ./results/

# Tube lengths mm:
# Inside Boxer Pumps = 65 (0,19ml)
# Inside DC Pumps = 150 (0.44ml)
# Bottle to Pump = 395 (1,15ml => 0,0029114 ml/mm)
# Mixer to Cell = 50+150+85 (0.83ml)
# Cell to Waste = 200+95+.. (0.86ml)
# Waste Length = 300 (0.88ml)
# Waste Spacing = 110 (0.32ml)

# Pumps to Needles
# 1 = 100 (0.29)
# 2 = 160 (0.47)
# 3 = 160 (0.47)
# 4 = 200 (0.58)
# 5 = 240 (0.7)

# Map each chemical to its controller/pump index and prime volume to fill the tubing.
# pump_index is 1..4 for each controller, cost is per ml

chemicals:
  Milli-Q: { controller: A, pump_index: 1, prime_ml: 1.8, cost: 1 } 
  Standard_1413u: { controller: A, pump_index: 2, prime_ml: 1.9, cost: 1 } 
  HCl: { controller: A, pump_index: 3, prime_ml: 1.9, cost: 1 }
  Na2SO4_2M: { controller: A, pump_index: 4, prime_ml: 2.1, cost: 5 }
  Ethanol: { controller: B, pump_index: 1, prime_ml: 2.2, cost: 1 }
  Chem6: { controller: B, pump_index: 2, prime_ml: 1.0, cost: 1 }
  Chem7: { controller: B, pump_index: 3, prime_ml: 1.0, cost: 1 }
  Chem8: { controller: B, pump_index: 4, prime_ml: 1.0, cost: 1 }

system:
  # Tube volumes between destinations (ml)
  mix_to_cell_ml: 0.83
  cell_to_waste_ml: 2.5
  waste_no: 1 # 1..4

# Default pump parameters used by the scheduler for priming / dosing.
pumps:
  # Calibration for stepper pumps (currently hardcoded in firmware)
  ml_per_rev: 0.094
  mixing_flowrate: 0.1 # ml/s
  priming_flowrate: 0.15
  # Calibration for DC pumps
  transfer_pwm: 40 # %
  waste_pwm: 40
  mixing_pwm: 80
  ml_per_s: 0.2

temperature:
  tolerance_C: 0.25 # plus or minus
  steady_s: 60
  timeout_s: 1800
  settle_s: 30

communication:
  pump_controller_A: # Has 2x DC transfer pumps
    ble_name: PumpControllerA
    mock: True
    timeout: 60
    ble: True
    port: /dev/cu.usbserial-CLEBb136G04
    baud: 115200

  pump_controller_B: # Has 4x DC waste pumps
    ble_name: PumpControllerB
    mock: True
    timeout: 60
    ble: True
    port: /dev/cu.usbserial-CLEBb136G04
    baud: 115200

  temperature_controller:
    port: /dev/cu.usbserial-CLEBb136G04
    baud: 115200
    mock: True

  squidstat:
    port: /dev/cu.usbmodem13101
    channel: 0
    instrument: Plus2695
    mock: True