measurements:
  results_root: ./results/
  user: Wessel
  project: MOFESS
  electrolyte: KCl # Will be overwritten if new mixture is created.
  cell_constant: 3 # /cm
  electrolyte_volume: 1.5 # ml (must match atinary total volume)
  cell_volume: 2.4 # ml (used for transfer and cleaning)

# Map each chemical to its controller/pump index and prime volume to fill the tubing.
# pump_index is 1..4 for each controller, cost is per ml
chemicals:
  Milli-Q: { controller: A, pump_index: 1, prime_ml: 1.0, cost: 0.01 }
  Ethanol: { controller: A, pump_index: 2, prime_ml: 1.0, cost: 0.5 }
  KCl: { controller: A, pump_index: 3, prime_ml: 1.0, cost: 4 }
  Chem4: { controller: A, pump_index: 4, prime_ml: 1.0, cost: 1 }
  Chem5: { controller: B, pump_index: 1, prime_ml: 1.0, cost: 1 }
  Chem6: { controller: B, pump_index: 2, prime_ml: 1.0, cost: 1 }
  Chem7: { controller: B, pump_index: 3, prime_ml: 1.0, cost: 1 }
  Chem8: { controller: B, pump_index: 4, prime_ml: 1.0, cost: 1 }

system:
  # Tube volumes between destinations
  mix_to_cell_ml: 0.5
  cell_to_waste_ml: 2.0
  waste_no: 1 # 1..4

# Default pump parameters used by the scheduler for priming / dosing.
pumps:
  # Calibration for stepper pumps (currently hardcoded in firmware)
  ml_per_rev: 0.094
  mixing_flowrate: 0.05 # ml/s
  priming_flowrate: 0.25
  # Calibration for DC pumps
  transfer_pwm: 70 # %
  waste_pwm: 100
  ml_per_s: 0.5

temperature:
  setpoints_C: [30] #[0.0, 10.0, 20.0, 40.0]
  tolerance_C: 0.25 # plus or minus
  steady_s: 120
  timeout_s: 1800
  settle_s: 60
  cleaning_s: 60

eis:
  freq_start_Hz: 85000
  freq_end_Hz: 1
  amplitude_v: 0.01
  bias_v: 0
  ppd: 20
  measurements_per_temp: 3 # minimum to give error bars

cv:
  first_limit_V: -1.5
  second_limit_V: 1.5
  scan_rate: 0.1
  sampling_interval_s: 0.1
  cycles: 3
  measurements_per_temp: 3 # minimum to give error bars

communication:
  pump_controller_A: # Has 2x DC transfer pumps
    port: /dev/cu.wchusbserial10
    baud: 115200
    mock: False
    timeout: 60
    ble: True
    ble_name: PumpControllerA

  pump_controller_B: # Has 4x DC waste pumps
    port: COM6
    baud: 115200
    mock: False
    timeout: 60
    ble: True
    ble_name: PumpControllerB

  temperature_controller:
    port: COM9
    baud: 115200
    mock: True

  squidstat:
    port: COM11
    channel: 0
    instrument: Plus2695
    mock: True