metadata:
  user: Wessel
  project: MOFESS
  electrolyte: KCl
  cell_constant: 3.92           # /cm
  electrolyte_volume: 1.5    # ml (should match total mixture volume in recipe)
  cell_volume: 1.5           # ml

repeats: 1                   # repeats the WHOLE steps section

steps:
  #- action: ClearSystem

  #- action: Prime

  #- action: CleanSystem
  #  cleaning_agent: Ethanol  # optional; defaults exist
  #  flushing_agent: Milli-Q  # optional
  #  temperature_C: 50
  #  cleaning_time_s: 60

  - action: MakeMixture

  - action: TransferToCell

  - action: EIS
    temperatures_C: [30]
    freq_start_Hz: 85000
    freq_end_Hz: 1
    amplitude_v: 0.01
    bias_v: 0
    ppd: 20
    measurements_per_temp: 3

  - action: TransferToWaste

  #- action: Deprime
