metadata:
  user: Wessel
  project: MOFESS
  electrolyte: KCl
  cell_constant: 3.8         # /cm
  electrolyte_volume: 1.5    # ml (should match total mixture volume in recipe)
  cell_volume: 1.6           # ml

repeats: 1                   # repeats the WHOLE steps section

steps:
  - action: ClearSystem

  #- action: Prime

  #- action: CleanSystem
  #  cleaning_agent: Ethanol  # optional; defaults exist
  #  flushing_agent: Milli-Q  # optional
  #  temperature_C: 50
  #  cleaning_time_s: 60

  - action: MakeMixture

  - action: Mix
    mixing_time: 10
    mixing_cycles: 10

  - action: TransferToCell

  - action: EIS
    temperatures_C: [30]
    freq_start_Hz: 85000
    freq_end_Hz: 1
    amplitude_v: 0.01
    bias_v: 0
    ppd: 20
    measurements_per_temp: 3
    keep_on: True # keep temperature controller ON after measurements

  - action: CV
    temperatures_C: [30]
    first_limit_V: -1.5
    second_limit_V: 1.5
    scan_rate: 0.1
    sampling_interval_s: 0.01
    cycles: 3
    measurements_per_temp: 3
    keep_on: True

  - action: TransferToWaste

  #- action: Deprime
